server:
  context-path: /
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://10.10.139.161:3306/uaa?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.cache.use_second_level_cache: false
    hibernate:
      ddl-auto: update